const Joi = require("joi");

module.exports = {
	add_house: Joi.object({
		address: Joi.string().required().error(new Error('This field is required')),
		zip_code: Joi.string().required().error(new Error('This field is required')),
		city: Joi.string().max(70).required().error(new Error('This field is required, characters limit up to 70')),
		country: Joi.number().integer().required().error(new Error('This field is required, expected type integer')),
		type: Joi.number().integer().required().error(new Error('This field is required, expected type integer')),
		title: Joi.string().max(30).error(new Error('characters limit up to 30')),
		nb_rooms: Joi.number().integer().error(new Error('Expected type integer')),
		nb_bedrooms: Joi.number().integer().error(new Error('Expected type integer')),
		surface: Joi.number().integer().error(new Error('Expected type integer')),
		area: Joi.number().integer().error(new Error('Expected type integer')),
		floor: Joi.number().integer().error(new Error('Expected type integer')),
		description: Joi.string(),
		latitude: Joi.string().required().error(new Error('This field is required')),
		longitude: Joi.string().required().error(new Error('This field is required')),
		map: Joi.string(),
		internet: Joi.boolean().error(new Error('Expected type boolean')),
		washing_machine: Joi.boolean().error(new Error('Expected type boolean')),
		TV: Joi.boolean().error(new Error('Expected type boolean')),
		hoven: Joi.boolean().error(new Error('Expected type boolean')),
		microwave: Joi.boolean().error(new Error('Expected type boolean')),
		dishwasher: Joi.boolean().error(new Error('Expected type boolean')),
		bathtub: Joi.boolean().error(new Error('Expected type boolean')),
		shower: Joi.boolean().error(new Error('Expected type boolean')),
		parking: Joi.boolean().error(new Error('Expected type boolean')),
		customer_id: Joi.number().integer().error(new Error('This field is required')),
		validation: Joi.boolean().error(new Error('Expected type boolean')),
	}),

	update_house: Joi.object({
		address: Joi.string().required().error(new Error('This field is required')),
		zip_code: Joi.string().required().error(new Error('This field is required')),
		city: Joi.string().max(70).required().error(new Error('This field is required, characters limit up to 70')),
		country: Joi.number().integer().required().error(new Error('This field is required')),
		type: Joi.number().integer().required().error(new Error('This field is required')),
		title: Joi.string().max(30).error(new Error('characters limit up to 30')),
		nb_rooms: Joi.number().integer().error(new Error('expected type integer')),
		nb_bedrooms: Joi.number().integer().error(new Error('expected type integer')),
		surface: Joi.number().integer().error(new Error('expected type integer')),
		area: Joi.number().integer().error(new Error('expected type integer')),
		floor: Joi.number().integer().error(new Error('expected type integer')),
		description: Joi.string(),
		latitude: Joi.string().required().error(new Error('This field is required')),
		longitude: Joi.string().required().error(new Error('This field is required')),
		map: Joi.string(),
		internet: Joi.boolean().error(new Error('Expected type boolean')),
		washing_machine: Joi.boolean().error(new Error('Expected type boolean')),
		TV: Joi.boolean().error(new Error('Expected type boolean')),
		hoven: Joi.boolean().error(new Error('Expected type boolean')),
		microwave: Joi.boolean().error(new Error('Expected type boolean')),
		dishwasher: Joi.boolean().error(new Error('Expected type boolean')),
		bathtub: Joi.boolean().error(new Error('Expected type boolean')),
		shower: Joi.boolean().error(new Error('Expected type boolean')),
		parking: Joi.boolean().error(new Error('Expected type boolean')),
		customer_id: Joi.number().integer().error(new Error('This field is required')),
		validation: Joi.boolean().error(new Error('Expected type boolean')),
	}),
};
