@host = http://localhost:5000

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxMDIsImlhdCI6MTY0Mjk1MTA3OSwiZXhwIjoxNjQyOTUyODc5fQ.nBxtvr5CoLc2fH1SqAxZeBmY9JKk3Nic8mMUrqliiWY

@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxMDIsImlhdCI6MTY0Mjk1MTA3OSwiZXhwIjoxNjQyOTU4Mjc5fQ.tnkNtSjTZai1jDj_XKts-Ds3kRJHYj3hlmcBhXbL-S0

###
POST {{host}}/signup HTTP/1.1
content-type: application/json

    {
        "email": "a@a.com",
        "password": "Paradis13$",
		"repeat_password": "Paradis13$",
        "firstname": "a",
        "lastname": "a",
        "pseudo": "Abdul",
        "phone_number": "0134538467",
        "photo":"/src/customer_photos/customer123.jpg",
        "isAdmin": false
    }

###
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$"
}

###
POST {{host}}/token HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}
