@host = http://localhost:5000

# CUSTOMER

###
GET {{host}}/customers/1 HTTP/1.1
content-type: application/json

###
GET {{host}}/customers/ HTTP/1.1
content-type: application/json

###
POST {{host}}/customers HTTP/1.1
content-type: application/json

    {
        "email": "jemoustique@gmail.com",
        "password": "landrover",
		"repeat_password": "landrover",
        "firstname": "Jules-Edouard",
        "lastname": "Moustique",
        "pseudo": "",
        "phone_number": "0175492412",
        "photo":"/src/customer_photos/customer123.jpg",
        "role_id": 2
    }

###
PATCH {{host}}/customers/101 HTTP/1.1
content-type: application/json

{   
    "email": "ml@gmail.com",
    "password": "landrover69D-_$@#!?",
	"repeat_password": "landrover69D-_$@#!?",
    "firstname": "Jules-Edouard",
    "lastname": "Moustique",
    "pseudo": "",
    "phone_number": "0175492412",
    "photo":"/src/customer_photos/customer123.jpg",
	"role_id": 2
}

###
DELETE {{host}}/customers/101 HTTP/1.1
content-type: application/json