@host = http://localhost:5000

# CUSTOMER

###
GET {{host}}/customers HTTP/1.1
content-type: application/json

###
GET {{host}}/customers/1 HTTP/1.1
content-type: application/json

###
PATCH {{host}}/customers/101 HTTP/1.1
content-type: application/json

{   
        "email": "juleedouardmousitque@gmail.com",
        "password": "landrover",
		"repeat_password": "landrover",
        "firstname": "Jules-Edouard",
        "lastname": "Moustique",
        "pseudo": "",
        "phone_number": "0175492412",
        "photo":"/src/customer_photos/customer123.jpg",
        "role_id": 2
}

###
DELETE {{host}}/customers/101 HTTP/1.1
content-type: application/json