-- Verify oparadis:init on pg

BEGIN;

SELECT * FROM CUSTOMER WHERE false;
SELECT * FROM CONNECTION WHERE false;
SELECT * FROM ANIMAL WHERE false;
SELECT * FROM HOUSE WHERE false;
SELECT * FROM PHOTO WHERE false;
SELECT * FROM ABSENTEE WHERE false;
SELECT * FROM ROLE WHERE false;
SELECT * FROM HOUSE_TYPE WHERE false;

ROLLBACK;
