@host = https://oparadisapi.herokuapp.com

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxMDEsImlhdCI6MTY0MzAzMDcyMSwiZXhwIjoxNjQzMDMwNzUxfQ.-_F14vPYc5mXDPNgpYiwsVo_LeaZTEw93zc05goBIiw

@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxMDIsImlhdCI6MTY0MzMwMDExOSwiZXhwIjoxNjQzMzAzNzE5fQ.VvmYygFEQPo_WvFG_TAFRO4r5aAL5ZYvut3hZdp_wMw

POST {{host}}/signup HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$",
    "repeat_password": "Paradis13$",
    "firstname": "a",
    "lastname": "a",
    "pseudo": "Abdul",
    "phone_number": "0134538467",
    "avatar":"/src/customer_photos/customer123.jpg"
}

###
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$"
}

###
POST {{host}}/token HTTP/1.1
content-type: application/json
Authorization: Bearer {{refresh_token}}

###
DELETE {{host}}/logout HTTP/1.1
content-type: application/json
Authorization: Bearer {{refresh_token}}
