@host = https://oparadisapi.herokuapp.com

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxMDEsImlhdCI6MTY0MzAzMDcyMSwiZXhwIjoxNjQzMDMwNzUxfQ.-_F14vPYc5mXDPNgpYiwsVo_LeaZTEw93zc05goBIiw

@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxMDcsImlhdCI6MTY0MzIxMzQwNywiZXhwIjoxNjQzMjE3MDA3fQ.weWgjn-sgmI4NZRp3HD21p4Ba8fynMpvwuqUDn6ECfc

###
POST {{host}}/signup HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$",
    "repeat_password": "Paradis13$",
    "firstname": "a",
    "lastname": "a",
    "pseudo": "Abdul",
    "phone_number": "0134538467",
    "avatar":"/src/customer_photos/customer123.jpg"
}

### Connexion User
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$"
}

### Update Password
PATCH {{host}}/customers/102/password HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "ancient_password": "Paradis12$",
    "password": "Paradis13$",
    "repeat_password": "Paradis13$"
}


###
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "o@o.com",
	"password": "Paradis13$"
}

###
POST {{host}}/token HTTP/1.1
content-type: application/json
Authorization: Bearer {{refresh_token}}

###
DELETE {{host}}/logout HTTP/1.1
content-type: application/json
Authorization: Bearer {{refresh_token}}