-- Revert oparadis:init from pg

BEGIN;

DROP TRIGGER IF EXISTS set_timestamp ON CUSTOMER;
DROP TRIGGER IF EXISTS set_timestamp ON HOUSE;
DROP TRIGGER IF EXISTS set_timestamp ON ANIMAL;
DROP TRIGGER IF EXISTS set_timestamp ON PLANT;
DROP TRIGGER IF EXISTS set_timestamp ON PHOTO;

DROP FUNCTION IF EXISTS trigger_set_timestamp;

DROP TRIGGER IF EXISTS set_pseudo ON CUSTOMER;

DROP FUNCTION IF EXISTS trigger_set_pseudo;

DROP TABLE IF EXISTS CUSTOMER, CONNECTION, ANIMAL, house_type, COUNTRY, HOUSE, PLANT, PHOTO, ABSENTEE CASCADE;

COMMIT;
