@host = http://localhost:5000

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMDIsImVtYWlsIjoiYUBhLmNvbSIsImZpcnN0bmFtZSI6ImEiLCJsYXN0bmFtZSI6ImEiLCJwc2V1ZG8iOiJBYmR1bCIsInBob25lX251bWJlciI6IjAxNjEyODYzOTciLCJhdmF0YXIiOm51bGwsImlzYWRtaW4iOmZhbHNlLCJjcmVhdGVkX2F0IjoiMjAyMi0wMS0yNlQxNzo0MDo0OC4wNDBaIiwidXBkYXRlZF9hdCI6IjIwMjItMDEtMjlUMTY6MTc6MDcuNzU1WiJ9LCJpYXQiOjE2NDM0NzMwNzQsImV4cCI6MTY0MzQ3MzM3NH0.g8LNdwEl9fR1UqsLv806vyoWmdOqoqVVRaBj-WEZZNU

@refresh_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMDIsImVtYWlsIjoiYUBhLmNvbSIsImZpcnN0bmFtZSI6ImEiLCJsYXN0bmFtZSI6ImEiLCJwc2V1ZG8iOiJBYmR1bCIsInBob25lX251bWJlciI6IjAxNjEyODYzOTciLCJhdmF0YXIiOm51bGwsImlzYWRtaW4iOmZhbHNlLCJjcmVhdGVkX2F0IjoiMjAyMi0wMS0yNlQxNzo0MDo0OC4wNDBaIiwidXBkYXRlZF9hdCI6IjIwMjItMDEtMjlUMTY6MTg6MzUuNTE4WiJ9LCJpYXQiOjE2NDM1NTgwMTcsImV4cCI6MTY0MzU2MTYxN30.JmWgI3LXkRADaL18o1qDft5IGaneh78ztjohez5g4co

###
POST {{host}}/signup HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$",
    "repeat_password": "Paradis13$",
    "firstname": "a",
    "lastname": "a",
    "pseudo": "Abdul",
    "phone_number": "0134538467",
    "avatar":"/src/customer_photos/customer123.jpg"
}

### Connexion User
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$"
}

### Update Password
PATCH {{host}}/customers/102/password HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

{
    "ancient_password": "Paradis12$",
    "password": "Paradis13$",
    "repeat_password": "Paradis13$"
}


###
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "kerstone@gmail.com",
	"password": "3GNCA35P18PDF6H9B"
}

###
POST {{host}}/token HTTP/1.1
content-type: application/json
Authorization: {{refresh_token}}

###
DELETE {{host}}/logout HTTP/1.1
content-type: application/json
Authorization: {{refresh_token}}