@host = http://localhost:5000

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMDEsImVtYWlsIjoia2Vyc3RvbmVAZ21haWwuY29tIiwiZmlyc3RuYW1lIjoiQ2hhcmxlcyIsImxhc3RuYW1lIjoiUGVndXkiLCJwc2V1ZG8iOiJLZXJzdG9uZSIsInBob25lX251bWJlciI6IjAxNjMyMDAzOTAiLCJhdmF0YXIiOm51bGwsImlzYWRtaW4iOnRydWUsImNyZWF0ZWRfYXQiOiIyMDIyLTAxLTI2VDE3OjQwOjQ3Ljg4MFoiLCJ1cGRhdGVkX2F0IjoiMjAyMi0wMS0yNlQxNzo0MDo0Ny44ODBaIn0sImlhdCI6MTY0MzQ2MzA3MSwiZXhwIjoxNjQzNDYzMzcxfQ.iZpbXZdNvi1ygMvMgi2OjY3uYKSaUJv_cKov039NbpA

@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMDEsImVtYWlsIjoia2Vyc3RvbmVAZ21haWwuY29tIiwiZmlyc3RuYW1lIjoiQ2hhcmxlcyIsImxhc3RuYW1lIjoiUGVndXkiLCJwc2V1ZG8iOiJLZXJzdG9uZSIsInBob25lX251bWJlciI6IjAxNjMyMDAzOTAiLCJhdmF0YXIiOm51bGwsImlzYWRtaW4iOnRydWUsImNyZWF0ZWRfYXQiOiIyMDIyLTAxLTI2VDE3OjQwOjQ3Ljg4MFoiLCJ1cGRhdGVkX2F0IjoiMjAyMi0wMS0yNlQxNzo0MDo0Ny44ODBaIn0sImlhdCI6MTY0MzQ2MzA3MSwiZXhwIjoxNjQzNDY2NjcxfQ.YtH5y13HDt7TzWuTLPSghg2NpqNNmv2aGQSG7smixnE

###
POST {{host}}/signup HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$",
    "repeat_password": "Paradis13$",
    "firstname": "a",
    "lastname": "a",
    "pseudo": "Abdul",
    "phone_number": "0134538467",
    "avatar":"/src/customer_photos/customer123.jpg"
}

###
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$"
}

###
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "kerstone@gmail.com",
	"password": "3GNCA35P18PDF6H9B"
}

###
POST {{host}}/token HTTP/1.1
content-type: application/json
Authorization: Bearer {{refresh_token}}

###
DELETE {{host}}/logout HTTP/1.1
content-type: application/json
Authorization: Bearer {{refresh_token}}