@host = http://localhost:5000

@access_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMDIsImVtYWlsIjoiYUBhLmNvbSIsImZpcnN0bmFtZSI6ImEiLCJsYXN0bmFtZSI6ImEiLCJwc2V1ZG8iOiJBYmR1bCIsInBob25lX251bWJlciI6IjAxNjEyODYzOTciLCJhdmF0YXIiOm51bGwsImlzYWRtaW4iOmZhbHNlLCJjcmVhdGVkX2F0IjoiMjAyMi0wMS0yNlQxNzo0MDo0OC4wNDBaIiwidXBkYXRlZF9hdCI6IjIwMjItMDEtMjlUMTY6MTg6MzUuNTE4WiJ9LCJpYXQiOjE2NDM2Mjk1NjksImV4cCI6MTY0MzYyOTg2OX0.YRR0SrTnq6njF_epz7hls8Y0TbOIujFjlGU3ZBwRC6E

@refresh_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxMDIsImVtYWlsIjoiYUBhLmNvbSIsImZpcnN0bmFtZSI6ImEiLCJsYXN0bmFtZSI6ImEiLCJwc2V1ZG8iOiJBYmR1bCIsInBob25lX251bWJlciI6IjAxNjEyODYzOTciLCJhdmF0YXIiOm51bGwsImlzYWRtaW4iOmZhbHNlLCJjcmVhdGVkX2F0IjoiMjAyMi0wMS0yNlQxNzo0MDo0OC4wNDBaIiwidXBkYXRlZF9hdCI6IjIwMjItMDEtMjlUMTY6MTg6MzUuNTE4WiJ9LCJpYXQiOjE2NDM2Mjk4MzMsImV4cCI6MTY0MzYzMzQzM30.USMidPfJ7BraxlOkNc3x8sUqOkhEqjVOw3tMeDdfAAc

###
POST {{host}}/signup HTTP/1.1
content-type: application/json

{
    "email": "o@o.com",
    "password": "Paradis13$",
    "repeat_password": "Paradis13$",
    "firstname": "o",
    "lastname": "o",
    "pseudo": "Jacquou le croquant",
    "phone_number": "0184546417",
    "avatar":"/src/customer_photos/customer126.jpg"
}

### Connexion User
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "a@a.com",
    "password": "Paradis13$"
}

### Update Password
PATCH {{host}}/customers/102/password HTTP/1.1
content-type: application/json
Authorization: {{access_token}}

{
    "ancient_password": "Paradis12$",
    "password": "Paradis13$",
    "repeat_password": "Paradis13$"
}


###
POST {{host}}/signin HTTP/1.1
content-type: application/json

{
    "email": "o@o.com",
	"password": "Paradis13$"
}

###
POST {{host}}/token HTTP/1.1
content-type: application/json
Authorization: {{refresh_token}}

###
DELETE {{host}}/logout HTTP/1.1
content-type: application/json
Authorization: {{refresh_token}}