@host = http://localhost:5000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxMDEsImlhdCI6MTY0MzAyODQyNCwiZXhwIjoxNjQzMDMwMjI0fQ.p1AmWLcqWtwrWj-O5jM1DEzvaVmcJ7KifZ7-2ItrdTk

# CUSTOMER

###
GET {{host}}/customers HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


###
GET {{host}}/customers/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


###
PATCH {{host}}/customers/101 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "email": "a@a.com",
    "password": "Paradis13$",
    "repeat_password": "Paradis13$",
    "firstname": "Misa",
    "lastname": "JarJar Binks",
    "pseudo": "Kerstone",
    "phone_number": "0134538467",
    "photo":"/src/customer_photos/customer25.jpg",
    "isAdmin": true
}

###
DELETE {{host}}/customers/101 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}
