@host = http://localhost:5000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxMDMsImlhdCI6MTY0MzIwMzEzOSwiZXhwIjoxNjQzMjAzMTY5fQ.i7gqD8WXtMMr54cedvi5jQRk51TBJqtW1fm81AglsEk
# CUSTOMER

###
GET {{host}}/customers HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


###
GET {{host}}/customers/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}


###
PATCH {{host}}/customers/101 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "email": "a@a.com",
    "password": "Paradis13$",
    "repeat_password": "Paradis13$",
    "firstname": "Misa",
    "lastname": "JarJar Binks",
    "pseudo": "Kerstone",
    "phone_number": "0134538467",
    "photo":"/src/customer_photos/customer25.jpg",
    "isAdmin": true
}

###
PATCH {{host}}/customers/107/password HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "password": "Paradis12$",
    "repeat_password": "Paradis12$"
}

###
DELETE {{host}}/customers/101 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}
